# Generated by Django 5.2.8 on 2025-12-03 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0002_tbl_usuario_sobrenome'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tbl_status_livro',
            options={'verbose_name': 'Status do Livro', 'verbose_name_plural': 'Status dos Livros'},
        ),
        migrations.AddField(
            model_name='tbl_status_livro',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterModelTable(
            name='tbl_status_livro',
            table='tbl_status_livro',
        ),
    ]
