# Generated by Django 5.2.8 on 2025-12-03 14:39

import biblioteca.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0003_alter_tbl_status_livro_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_livro',
            name='capa',
            field=models.ImageField(blank=True, null=True, upload_to=biblioteca.models.livro_capa_upload_path, verbose_name='Capa do Livro'),
        ),
    ]
