# Generated by Django 5.2.8 on 2025-12-12 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0010_tbl_livro_disponivel'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_livro',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
